### ISSUE TITLE
Include documentation for adding ESP32 functionality and standalone displays

### ISSUE THREAD

**Issue by ghost** [botletics/Reflowdiuno#1]
I think adding some documentation for adding ESP32 modules and standalone displays would be great. There should be enough IO pins left for both, AFAIK.

**Comment by botletics** [comment]
Hi there, thanks for the suggestion! Sorry I didn't see this earlier. Adding support for display shields is currently in the [to-do list](https://github.com/botletics/Reflowduino/wiki/To-Do-List) and ESP32 support sounds fun (although I'm not sure how one would use the ESP32 with the reflow oven application)! I'll keep you updated when I add display support. In the meantime I'm launching an Indiegogo campaign for Reflowduino on December 1st!

**Comment by VinnyCordeiro** [comment]
There was a project of a reflow oven called [Reflow Château](https://hackaday.com/2015/02/02/reflow-chateau/) that appeared in 2015 on Hackaday that uses a Teensy 3.1 and a graphic touchscreen display. The [original website of the project is down](https://web.archive.org/web/20160114235200/http://www.willfj.com/reflow-chateau/) (Internet Archive link for it works) but there is a copy of it here on Github. I've made [a fork of it](https://github.com/VinnyCordeiro/ReflowChateau), as there are some missing files in the original repo.

The controller works but uses obsolete/discontinued components, namely the thermocouple IC and the solid-state relays. I had the idea to update the project, but never had the time to really do that. I hope that this project will help to improve yours. The original project uses the Apache License, so it's open source.

**Comment by botletics** [comment]
Awesome, thanks! I'll check it out when I get a chance.

**Comment by ghost** [comment]
I might be able to work on this soon, just got a Xmas sized lot of components and boards that are too much of a PITA to do without a reflow oven.

**Comment by botletics** [comment]
I'm working on making an Instructables tutorial and YouTube video about how to build a BLE Android app for the ESP32. Stay tuned! Maybe I could also build a custom PCB that uses the ESP32 dev board as the controller that snaps into some headers?!?!

**Comment by botletics** [comment]
I just posted an Instructable on how to make an Android app for two-way communication with an ESP32 using Arduino IDE! Check it out [here](https://www.instructables.com/id/ESP32-BLE-Android-App-Arduino-IDE-AWESOME/)!

**Comment by tedder** [comment]
esp32? ooo. I've been modding my 'duino and figure I'll switch to an esp32, perhaps a wemos-with-OLED one. hmm.

**Comment by botletics** [comment]
Haha yea that would have to be a completely separate board but it's doable. Just a matter of when I can find time for such things  :)

**Comment by tedder** [comment]
Right, it'll replace the 32u4. No reason to interface with it. I'm just glad to see others may be interested in it.

**Comment by botletics** [comment]
Just added ESP32 support! I made a "backpack" module for this [DOIT ESP32 dev board](https://www.amazon.com/Docreate-Development-Bluetooth-Ultra-Low-Consumption/dp/B0754DT83W/ref=sr_1_3?ie=UTF8&qid=1521924528&sr=8-3&keywords=esp32). Check out the [demo code for it here](https://github.com/botletics/Reflowduino/tree/master/Example%20Code/Reflowduino_ESP32_Demo)!
