### ISSUE TITLE
?Error in ramping calculation

### ISSUE THREAD

**Issue by sticilface** [botletics/Reflowdiuno#5]
https://github.com/botletics/Reflowduino/blob/282cc685d3a3602490819a8b25ddf43d04c131eb/Example%20Code/Reflowduino_Demo/Reflowduino_Demo.ino#L205

Your units for rate are Deg per second not per ms.  So you calculate projected time in seconds but then add it to mills(); 

should it not be
```cpp
t_final = (T_preheat - T_start) /  (preheat_rate / 1000)  + t_start;
```

Correct me if i'm wrong.

**Comment by botletics** [comment]
Oh yes you're right, thanks for catching that! I somehow didn't convert all the rates to *C/ms. What you could do is just divide preheat_rate by 1000 up top where it's first defined or create a pull request to divide by 1000 for the rates.

**Comment by botletics** [comment]
Fixed the code, thanks!
