### ISSUE TITLE
About ESP32 Bluetooth lib.

### ISSUE THREAD

**Issue by icebabycool** [botletics/Reflowdiuno#7]
Hi there botletics, i`ve been try your ESP32 version code for do it on my own, but i can`t find some libraries that you used in ESP32.ino, they are:
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>

So may i ask you to addd these in to the project folder? Thanks!

**Comment by botletics** [comment]
Please see [this wiki page](https://github.com/botletics/Reflowduino/wiki/ESP32-Arduino-Setup)
